version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ..:/app
